# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Taboola SDK ObjC Samples' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/taboola/taboola-cocopods.git'
  
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'TaboolaSDK', '2.3.0'
  # Pods for Taboola SDK ObjC Samples

end
