# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Taboola SDK Swift Sample' do
use_frameworks!
pod 'TaboolaSDK', '2.3.9'
end

target 'TaboolaSDKSwiftSampleTests' do
use_frameworks!
pod 'TaboolaSDK', '2.3.9'

end
