# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/taboola/taboola-cocopods.git'

source 'https://github.com/CocoaPods/Specs.git'


target 'Taboola SDK Swift Sample' do
use_frameworks!
pod 'TaboolaSDK', '2.3.8'
end

target 'TaboolaSDKSwiftSampleTests' do
use_frameworks!
pod 'TaboolaSDK', '2.3.8'
end


